#PYTHON WILL GENERATE a random no and the user will give i/p... if the i/p matches with that random no generated by the python, then u will win the game..
#THIS IS OUR 1st Mini Project:-> GUESS THE NUMBER..
#for this we need to use an (inbuilt Function) in Python which belongs to RANDOM Module of Python which will help us 2 generate random numbers or random letters,random characters etc etc
import random

randomNo = random.randint(1,5 ) #randint is a func in RANDOM Module which is used for generating random ints and this func will take 2 values a and b and a aur b ke range ke andar ke kisi bhi value ko yeh generate kartaa hain
print(randomNo) #ek baar ke o/p me 1 generate karega, dusri baar 3 ya may be 4 , aise tisri baar 5 generate karega, o/p ko 2 ya 3 baar run karke dekho, toh idea ho jayega

#lets start our MINI PROJECT now,lets suppose our range is 1-100 ,means is range ke andar kisi v number ko guess karnaa hain,agar random no jo generate karega program wo user jo input dega uske saath match ho gayaa, then u win
target = random.randint(1,100)

while True: #conditiom true tab tak chalegaa jab tak user ka i/p target ke saath match hoga, ab yeh uncertain hain, luck agar saath ho toh hi match hoga isiliye condition humne true diya,infinite loop nhi hoga b/c once the target matches the user's i/p we will apply break in b/w the program which will stop the loop
    userChoice = input("guess the no or Quit(Q)")
    if(userChoice=="Q"): #jaise hi humne Quit likha , hum pure while loop se baahar ho jayenge and lastly in the o/p , line 26 will be printed which means GAME OVER
        break


    userChoice = int(userChoice) #agar Quit nhi karte hain toh hum apne input ko integer value me convert kar denge taki program i/p lekar execute kar sakein
    if(userChoice==target):
        print("success, u guessed the correct no")
        break

    elif(userChoice>target):
        print("ur number is slightly bigger than the generated no. Take a smaller guess")
    else:
        print("ur number is slightly smaller than the generated no. Take a bigger guess")

print("GAME OVER")